dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.38
- alias: prow
  name: prow
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.620
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
  version: 2.0.276
